#!/bin/bash

if [ "$1" == "install" ]; then
	echo "==============================="
	echo "Sigma"
	echo "==============================="
	wget -q -P ~/.pix/ "raw.githubusercontent.com/progwi0/pix-repo/main/$2.bin"
	chmod +777 ~/.pix/$2.bin
	echo "==============================="
	echo "$2 installed. Type 'pix run $2' to run it."
	echo "==============================="
	echo " ________"
	echo "/____...|_"
	echo "|____|..|.|"
	echo "|.......|_"
	echo "|__|.|__|"
	echo "==============================="
elif [ "$1" == "remove" ]; then
	echo "==============================="
	echo "Not sigma"
	echo "==============================="
	rm ~/.pix/$2.bin
	echo "==============================="
	echo "$2 removed."
	echo "==============================="
	echo " ________"
	echo "/____...|_"
	echo "|____|..|.|"
	echo "|.......|_"
	echo "|__|.|__|"
	echo "==============================="
elif [ "$1" == "run" ]; then
	~/.pix/$2.bin
	echo "==============================="
	echo "Ultra sigma"
	echo "==============================="
	echo " ________"
	echo "/____...|_"
	echo "|____|..|.|"
	echo "|.......|_"
	echo "|__|.|__|"
	echo "==============================="
elif [ "$1" == "help" ]; then
	echo "==============================="
	echo "PIX HELP"
	echo "==============================="
	echo "pix install - install package"
	echo "pix remove - remove package"
	echo "pix run - run package"
	echo "pix version - show pix version"
	echo "pix help - show help"
	echo "==============================="
	echo " ________"
	echo "/____...|_"
	echo "|____|..|.|"
	echo "|.......|_"
	echo "|__|.|__|"
	echo "==============================="
elif [ "$1" == "version" ]; then
	echo "==============================="
	echo "PIX 2.0"
	echo "==============================="
	echo " ________"
	echo "/____...|_"
	echo "|____|..|.|"
	echo "|.......|_"
	echo "|__|.|__|"
	echo "==============================="
else
	echo "Unknown argument. For help u can type 'help'!"
fi
